(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.Logger = f()}})(function(){var define,module,exports;return (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var level_1 = require("./level");
var loggerManager_1 = require("./loggerManager");
/**
 * **(You should not use this class directly)**
 *
 * This is an internal class used to manage the actual logging.
 *
 * This simply calls the corresponding *console* method to log in the browser console.
 */
var Display = /** @class */ (function () {
    function Display() {
    }
    /**
     * Method that acts as a proxy to the *console*
     * @param message The initial string after the *moduleName*; this will be enclosed in a rectangular border of the corresponding color
     * @param params Topically the objects to log
     * @param moduleName The name of the logger
     * @param moduleColor The color associated to the logger
     * @param level Type of log (i.e. DEBUG, INFO, etc...)
     * @param moduleWidth Width of the logger name. If the *moduleName* is less than this spaces will be added as padding.
     */
    Display.msg = function (message, params, moduleName, moduleColor, level, moduleWidth) {
        if (loggerManager_1.LoggerManager.isProductionMode() ||
            !loggerManager_1.LoggerManager.isLevelAllowed(level) ||
            loggerManager_1.LoggerManager.isMuted(moduleName))
            return;
        var color;
        switch (level) {
            case level_1.Level.DEBUG:
                color = 'violet';
                break;
            case level_1.Level.ERROR:
                color = 'red';
                break;
            case level_1.Level.INFO:
                color = 'deepskyblue';
                break;
            case level_1.Level.LOG:
                color = 'gray';
                break;
            case level_1.Level.WARN:
                color = 'orange';
                break;
        }
        if (moduleWidth) {
            var diff = moduleWidth - moduleName.length;
            if (diff > 0) {
                for (var i = 0; i < diff; i++) {
                    moduleName += ' ';
                }
            }
        }
        var a1 = '%c ' + moduleName + '  %c ' + message + ' ';
        var a2 = 'background: ' + moduleColor + ';color:white; border: 1px solid ' + moduleColor + '; ';
        var a3 = 'border: 1px solid ' + color + '; ';
        params = params[0];
        params.unshift(a3);
        params.unshift(a2);
        params.unshift(a1);
        // _console.log.apply(_console, params);
        switch (level) {
            case level_1.Level.INFO:
                console.info.apply(console, params);
                break;
            case level_1.Level.DEBUG:
                console.debug.apply(console, params);
                break;
            case level_1.Level.LOG:
                console.log.apply(console, params);
                break;
            case level_1.Level.WARN:
                console.warn.apply(console, params);
                break;
            case level_1.Level.ERROR:
                console.error.apply(console, params);
                break;
        }
    };
    return Display;
}());
exports.Display = Display;

},{"./level":3,"./loggerManager":5}],2:[function(require,module,exports){
"use strict";
/**
 * @file Automatically generated by barrelsby.
 */
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./display"));
__export(require("./level"));
__export(require("./logger"));
__export(require("./loggerManager"));

},{"./display":1,"./level":3,"./logger":4,"./loggerManager":5}],3:[function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Supported levels of logging. Each one sets a color as border of the message in the log
 */
var Level;
(function (Level) {
    /**
     * This gives a blue border to the message
     */
    Level[Level["INFO"] = 0] = "INFO";
    /**
     * This gives a black border to the message
     */
    Level[Level["LOG"] = 1] = "LOG";
    /**
     * This gives a violet border to the message
     */
    Level[Level["DEBUG"] = 2] = "DEBUG";
    /**
     * This gives a orange border to the message
     */
    Level[Level["WARN"] = 3] = "WARN";
    /**
     * This gives a red border to the message
     */
    Level[Level["ERROR"] = 4] = "ERROR";
})(Level = exports.Level || (exports.Level = {}));

},{}],4:[function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var level_1 = require("./level");
var display_1 = require("./display");
/**
 * **(You should not use this class directly)**
 *
 * This is the logger created by the *LoggerManager*, it has all the methods to allow different levels of logging.
 * Every level has a color as border for the message.
 */
var Logger = /** @class */ (function () {
    /**
     *
     * @param name Logger name, this is the first information written for each log created
     * @param color Color of the background for the *name* in the log. This can be any CSS color name or hexadecimal string. You can set the color also after the creation of the logger
     * @param fixedWidth Width of the logger name part, if passed and the *name* is shorter than padding will be added to reach the width
     */
    function Logger(name, color, fixedWidth) {
        this.name = name;
        this.color = color;
        this.fixedWidth = fixedWidth;
    }
    /**
     * This logs a message and the data with *Level.DEBUG*
     * @param message A message to print along the logger name
     * @param data The optional data to log
     */
    Logger.prototype.debug = function (message) {
        var data = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            data[_i - 1] = arguments[_i];
        }
        return this._logMessage(message, level_1.Level.DEBUG, data);
    };
    /**
     * This logs a message and the data with *Level.DEBUG*
     * @param message A message to print along the logger name
     * @param data The optional data to log
     */
    Logger.prototype.log = function (message) {
        var data = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            data[_i - 1] = arguments[_i];
        }
        return this._logMessage(message, level_1.Level.LOG, data);
    };
    /**
     * This logs a message and the data with *Level.ERROR*
     * @param message A message to print along the logger name
     * @param data The optional data to log
     */
    Logger.prototype.error = function (message) {
        var data = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            data[_i - 1] = arguments[_i];
        }
        return this._logMessage(message, level_1.Level.ERROR, data);
    };
    /**
     * This logs a message and the data with *Level.INFO*
     * @param message A message to print along the logger name
     * @param data The optional data to log
     */
    Logger.prototype.info = function (message) {
        var data = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            data[_i - 1] = arguments[_i];
        }
        return this._logMessage(message, level_1.Level.INFO, data);
    };
    /**
     * This logs a message and the data with *Level.WARN*
     * @param message A message to print along the logger name
     * @param data The optional data to log
     */
    Logger.prototype.warn = function (message) {
        var data = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            data[_i - 1] = arguments[_i];
        }
        return this._logMessage(message, level_1.Level.WARN, data);
    };
    /**
     * Internal method that ask to the Display class to handle the log
     * @param message A message to print along the logger name
     * @param level Level associated to the log entry
     * @param data The optional data to log
     * @private
     */
    Logger.prototype._logMessage = function (message, level) {
        var data = [];
        for (var _i = 2; _i < arguments.length; _i++) {
            data[_i - 2] = arguments[_i];
        }
        display_1.Display.msg(message, data, this.name, this.color, level, this.fixedWidth);
        return this;
    };
    return Logger;
}());
exports.Logger = Logger;

},{"./display":1,"./level":3}],5:[function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var logger_1 = require("./logger");
var LoggerManager = /** @class */ (function () {
    function LoggerManager() {
    }
    LoggerManager.create = function (name, color) {
        var i;
        if (LoggerManager.instances[name] === undefined) {
            if (!LoggerManager.instancesStateMap.hasOwnProperty(name))
                //TODO save config when creating and add a default mute or unmute on creation
                LoggerManager.instancesStateMap[name] = false;
            i = new logger_1.Logger(name, color || LoggerManager.getRandomColor(), LoggerManager.levels.length > 0 ? LoggerManager.fixedWidth : undefined);
            LoggerManager.instances[name] = i;
        }
        else {
            i = LoggerManager.instances[name];
        }
        return i;
    };
    LoggerManager.onlyLevels = function () {
        var levels = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            levels[_i] = arguments[_i];
        }
        LoggerManager.levels = levels;
        LoggerManager.saveState();
    };
    LoggerManager.onlyModules = function () {
        var modules = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            modules[_i] = arguments[_i];
        }
        if (modules.length === 0)
            return;
        LoggerManager.muteAllModules();
        modules.forEach(function (m) { return LoggerManager.mute(m, false); });
    };
    LoggerManager.mute = function (moduleName, mute) {
        if (mute === void 0) { mute = true; }
        LoggerManager.instancesStateMap[moduleName] = mute;
        LoggerManager.saveState();
    };
    LoggerManager.unmute = function (moduleName) {
        LoggerManager.mute(moduleName, false);
    };
    LoggerManager.unMuteAllModules = function () {
        for (var moduleName in LoggerManager.instances) {
            LoggerManager.mute(moduleName, false);
        }
    };
    LoggerManager.muteAllModules = function () {
        for (var moduleName in LoggerManager.instances) {
            LoggerManager.mute(moduleName, true);
        }
    };
    LoggerManager.setProductionMode = function () {
        LoggerManager.DEV_MODE = false;
        delete window['LoggerManager'];
    };
    LoggerManager.isProductionMode = function () {
        return !LoggerManager.DEV_MODE;
    };
    LoggerManager.isMuted = function (moduleName) {
        return LoggerManager.instancesStateMap[moduleName];
    };
    LoggerManager.isLevelAllowed = function (level) {
        return LoggerManager.levels.length == 0 || LoggerManager.levels.includes(level);
    };
    LoggerManager.showConfig = function () {
        return {
            modulesState: LoggerManager.instancesStateMap,
            levels: LoggerManager.levels
        };
    };
    LoggerManager.getRandomColor = function () {
        // Source https://www.paulirish.com/2009/random-hex-color-code-snippets/
        return '#' + Math.floor(Math.random() * 16777215).toString(16);
    };
    LoggerManager.saveState = function () {
        var state = {
            map: LoggerManager.instancesStateMap,
            levels: LoggerManager.levels
        };
        localStorage.setItem(LoggerManager.STORAGE_KEY, JSON.stringify(state));
    };
    LoggerManager.loadState = function () {
        var state = localStorage.getItem(LoggerManager.STORAGE_KEY);
        if (state) {
            state = JSON.parse(state);
            LoggerManager.instancesStateMap = state.map;
            LoggerManager.levels = state.levels;
        }
    };
    LoggerManager.DEV_MODE = true;
    LoggerManager.STORAGE_KEY = 'typescript-logger-state';
    LoggerManager.instances = {};
    LoggerManager.instancesStateMap = {};
    LoggerManager.fixedWidth = 0;
    LoggerManager.levels = [];
    LoggerManager.initializationBlock = (function () {
        window['LoggerManager'] = {
            onlyLevel: LoggerManager.onlyLevels,
            onlyModules: LoggerManager.onlyModules,
            mute: LoggerManager.mute,
            unmute: LoggerManager.unmute,
            unMuteAllModules: LoggerManager.unMuteAllModules,
            muteAllModules: LoggerManager.muteAllModules,
            showConfig: LoggerManager.showConfig
        };
        LoggerManager.loadState();
    })();
    return LoggerManager;
}());
exports.LoggerManager = LoggerManager;

},{"./logger":4}]},{},[2])(2)
});
